version: '3.7'

services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000

# TODO Add backstop configuration - pass in env var and run all the scenarios in CI
